---
new_page_extension: md
auto_deploy: false
admin_path: "/control"
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/posts
  label: Posts
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: '0.44'
